final solution to chrome issue

diff --git a/.github/workflows/ciTest.yml b/.github/workflows/ciTest.yml
--- a/.github/workflows/ciTest.yml
+++ b/.github/workflows/ciTest.yml
@@ -41,6 +41,8 @@ jobs:
         run: |
           google-chrome --version || echo "Google Chrome not found"
           chromedriver --version || echo "ChromeDriver not found"
+          chrome --version || echo "Google Chrome not found"
+
 
       - name: Run Tests with Maven
         run: mvn test
